server:
  port: 8084

spring:
  cloud:
    gateway:
      routes:
        - id: api-gateway
          uri: http://localhost:8084
          predicates:
            - Path=/api/auth/**
        - id: hotel-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/hotels/**
        - id: reservation-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/reservations/**

  application:
    name: api-gateway